version: '0.0.1'

networks:
  app_network:
    driver: bridge

services:
  postgres:
    image: postgres:latest
    restart: always
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ParcelDeliveryAppDatabase
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app_network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/rw
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq:rw
    networks:
      - app_network

  api-gateway:
    image: api-gateway
    container_name: "api-gateway"
    restart: always
    environment:
      MS_USER: ms-user
      MS_ORDER: ms-order
      MS_DELIVERY: ms-delivery
    networks:
      - app_network
    ports:
      - "8080:8080"

  ms-user:
    image: ms-user
    container_name: "ms-user"
    restart: always
    networks:
      - app_network
    ports:
      - "8081:8081"
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ: rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq

  ms-order:
    image: ms-order
    container_name: "ms-order"
    restart: always
    networks:
      - app_network
    ports:
      - "8082:8082"
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ: rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq

  ms-delivery:
    image: ms-delivery
    container_name: "ms-delivery"
    restart: always
    networks:
      - app_network
    ports:
      - "8083:8083"
    environment:
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      RABBITMQ: rabbitmq
    depends_on:
      - postgres
      - rabbitmq
    links:
      - postgres
      - rabbitmq

