CREATE SCHEMA msuser;

CREATE TABLE IF NOT EXISTS msuser._role (
    id smallint generated by default as identity
       primary key,
    type varchar(255) not null
);

CREATE TABLE IF NOT EXISTS msuser._user(
    id  bigint generated by default as identity
        primary key,
    created_at timestamp    not null,
    is_active  boolean      not null,
    password   varchar(255) not null,
    updated_at timestamp    not null,
    username   varchar(255) not null
);

CREATE TABLE IF NOT EXISTS msuser.user_roles(
    user_id bigint   not null
        constraint fkcbsnrgq3e9qe6kuxq7wx6vlfm
            references msuser._user,
    role_id smallint not null
        constraint fkdbkmppm1giciadoymsekj0gp6
            references msuser._role,
    primary key (user_id, role_id)
);


INSERT INTO msuser._role (type) VALUES ('ADMIN');
INSERT INTO msuser._role (type) VALUES ('USER');
INSERT INTO msuser._role (type) VALUES ('COURIER');

INSERT INTO msuser._user (created_at, is_active, password, updated_at, username)
VALUES (now(), true, '$2a$10$/CqeiQKu1axsYuzdlGpgSeWlQUvIJsB.z7VFaWuvr7XcGXCpo/u26', now(), 'admin@gmail.com');

INSERT INTO msuser.user_roles (user_id, role_id) VALUES (1, 1);


CREATE SCHEMA msorder;

CREATE TABLE IF NOT EXISTS msorder._order (
    id  bigint generated by default as identity
        primary key,
    address_updated_by varchar(255) not null,
    created_at         timestamp    not null,
    delivery_address   varchar(255) not null,
    delivery_type      integer      not null,
    order_status       varchar(255) not null,
    parcel_id          bigint       not null,
    status_updated_by  varchar(255) not null,
    updated_at         timestamp    not null,
    user_id            bigint       not null
);

CREATE SCHEMA msdelivery;

CREATE TABLE IF NOT EXISTS msdelivery._courier (
    id  bigint generated by default as identity
        primary key,
    courier_status varchar(255) not null,
    courier_type   varchar(255) not null,
    created_at     timestamp    not null,
    is_active      boolean      not null,
    updated_at     timestamp    not null,
    username       varchar(255) not null
);

CREATE TABLE IF NOT EXISTS msdelivery._delivery (
    id  bigint generated by default as identity
        primary key,
    address_updated_by varchar(255) not null,
    courier_id         bigint,
    created_at         timestamp    not null,
    delivery_address   varchar(255) not null,
    delivery_type      integer      not null,
    estimated_delivery timestamp,
    order_status       varchar(255) not null,
    status_updated_by  varchar(255) not null,
    updated_at         timestamp    not null
);








