server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      enabled: true

app:
  jwt:
    secret: appsecretkey
  services:
    user: http://${MS_USER:localhost}
    order: http://${MS_ORDER:localhost}
    delivery: http://${MS_DELIVERY:localhost}