server:
  servlet:
    context-path: /api
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: info, health
  endpoint:
    health:
      enabled: true

app:
  jwt:
    secret: appsecretkey
    expiry: 86400

spring:

  rabbitmq:
    host: ${RABBITMQ:localhost}
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/ParcelDeliveryAppDatabase
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: false
    generate-ddl: false
    hibernate:
      ddl-auto: update
